"""Rasterize the office scene into a walkability mask.

Reads public/office/office_empty.png, classifies pixels as floor/rug (open)
or anything else (blocked), downsamples to a grid, applies hand overrides,
and writes src/lib/office/navmask.ts. Re-run after changing the artwork or
the overrides below:  python scripts/navmask.py
"""
from PIL import Image

SCENE = "public/office/office_empty.png"
OUT = "src/lib/office/navmask.ts"
N = 128            # grid is N x N cells over the square scene (~10px cells)
OPEN_RATIO = 0.85  # a cell is open only if nearly all of its pixels are floor/rug
CLEARANCE = 1      # cells of margin kept around anything blocked (feet stay off walls)

# Carpets are patterned, so inside these rooms a cell only needs to be mostly
# floor/rug to count as open; furniture on the carpet is still solid.
RUG_ZONES = [
    (0.05, 0.08, 0.31, 0.27),  # private office
    (0.13, 0.66, 0.43, 0.90),  # reception / lounge
    (0.60, 0.62, 0.95, 0.87),  # meeting room
]
RUG_RATIO = 0.5

# Floor tiles come in a few shades: the main floor, the shaded bottom-left
# rooms, and the darker patch by the reception desk.
FLOORS = [((218, 205, 196), 16), ((204, 185, 170), 14), ((188, 168, 154), 12)]
RUGS = [((94, 60, 69), 28), ((114, 81, 90), 28)]

# Hand overrides in scene fractions (x0, y0, x1, y1): force open / force blocked.
FORCE_OPEN = [
    (0.28, 0.245, 0.33, 0.36),    # private office: glass door at the right end of the partition
    (0.565, 0.735, 0.665, 0.83),  # meeting room: door in the left wall
]
FORCE_BLOCKED = []


def near(c, ref, tol):
    return all(abs(c[i] - ref[i]) <= tol for i in range(3))


def walkable(c):
    return any(near(c, ref, tol) for ref, tol in FLOORS + RUGS)


def main():
    im = Image.open(SCENE).convert("RGB")
    W, H = im.size
    px = im.load()
    rows = []
    for gy in range(N):
        row = ""
        for gx in range(N):
            x0, x1 = int(gx * W / N), int((gx + 1) * W / N)
            y0, y1 = int(gy * H / N), int((gy + 1) * H / N)
            tot = ok = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    tot += 1
                    ok += walkable(px[x, y])
            cx, cy = (gx + 0.5) / N, (gy + 0.5) / N
            on_rug = any(x0 <= cx <= x1 and y0 <= cy <= y1 for x0, y0, x1, y1 in RUG_ZONES)
            row += "." if ok / tot >= (RUG_RATIO if on_rug else OPEN_RATIO) else "#"
        rows.append(list(row))

    def apply(rects, ch):
        for x0, y0, x1, y1 in rects:
            for gy in range(int(y0 * N), min(N, int(y1 * N + 0.999))):
                for gx in range(int(x0 * N), min(N, int(x1 * N + 0.999))):
                    rows[gy][gx] = ch

    # Grow every blocked cell by CLEARANCE so walkers keep their feet clear of
    # walls and furniture instead of hugging them.
    src = [r[:] for r in rows]
    for gy in range(N):
        for gx in range(N):
            if src[gy][gx] != "#":
                continue
            for dy in range(-CLEARANCE, CLEARANCE + 1):
                for dx in range(-CLEARANCE, CLEARANCE + 1):
                    y, x = gy + dy, gx + dx
                    if 0 <= y < N and 0 <= x < N:
                        rows[y][x] = "#"

    apply(FORCE_OPEN, ".")
    apply(FORCE_BLOCKED, "#")

    body = ",\n".join(f'  "{"".join(r)}"' for r in rows)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// GENERATED by scripts/navmask.py from public/office/office_empty.png.\n"
            "// '#' = blocked (wall, furniture, outside), '.' = open floor. Each row is\n"
            "// one band of the scene, top to bottom. Edit the overrides in the script,\n"
            "// not this file.\n"
            f"export const NAV_ROWS: string[] = [\n{body},\n];\n"
        )
    print("\n".join("".join(r) for r in rows))


if __name__ == "__main__":
    main()
